id: I67766760
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:34:50+00:00'
last_modified: '2022-06-07T14:09:41.628003+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19960
  title: གཏོར་མ་བརྒྱ་རྩའི་རྣམ་པར་བཤད་པ་དང་དཀར་ཆ་བཞིའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B59:
      image_group_id: I8LS19962
      title: ''
      total_pages: 80
      order: 1
      base_file: 9B59.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
